### ISSUE TITLE
Prepare release 1.9 - TO-DO

### ISSUE THREAD

**Issue by ricsanfre** [ricsanfre/pi-cluster#475]
# TO-DO 

- [x] Cilium installation
  - [x] Kube-proxy and MetalLB replacement
  - [x] Huble and monitoring cofiguration
  - [x] Update documentation
    - [x] New Cilium CNI instalation document
    - [x] Include Cilium Hubble/monitoring documentation

- [x] Grafana deployment
  - [x] Deploy Grafana application decoupled from Kube-prometheus-stack
  - [x] Grafana dashboards folders configuration
  - [x] Grafana providers configuration (automatic load from Grafana Labs)
  - [x] Update documentation

- [x] Databases
  - [x] CloudNative-PG
    - [x] Deploy cloudnative-pg operator
    - [x] Migrate Keycloak DB to CloudNative-PG based database deployed in HA
    - [x] Configure database backup to external S3
    - [x] Update documentation

- [x] Istio
  - [x] Deploy Istio ambient mode
  - [x] Configure Istio observability
    - [x] Configure Prometheus monitoring
    - [x] Install Kiali
    - [x] Integrate with Prometheus Tempo and grafana
    - [x] Configure Kiali Open ID authentication
  - [x] Update doc

- [x] FluxCD
  - [x] Flux CD deployment
  - [x] Redefine the structure of the GitOps repo
     - [x] Refactor kubernetes applications
     - [x] Include Kustomize advanced configurations
        - [x] Components
     - [x] Include Flux advanced configuration
        - [x] Helm values from ConfigMaps
        - [x] Variables subsitution 
  - [x] Update cluster bootstraping process 
  - [x] Update doc

- [x] Backup
  - [x] Update Velero to 1.14
  - [x] Update restic to latest version
  - [x] Update documentation
